const LEFT_MENU_TREE = [{
    "target": "_self", "url": "#wodegongzuotai", "pId": "0", "children": [{
        "target": "_self",
        "url": "#xitongguanli",
        "pId": "1",
        "children": [{
            "target": "_self",
            "url": "#gongsidingyi",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "3",
            "name": "公司定义"
        }, {
            "target": "_self",
            "url": "#xitongcanshu",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "4",
            "name": "系统参数"
        }, {
            "target": "_self",
            "url": "#caozuoyuandangan",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "5",
            "name": "操作员档案"
        }, {
            "target": "_self",
            "url": "#danjuhaoguanli",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "6",
            "name": "单据号管理"
        }, {
            "target": "_self",
            "url": "#huijizhouqi",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "7",
            "name": "会计周期"
        }, {
            "target": "_self",
            "url": "#qiyongzhangtao",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "8",
            "name": "启用帐套"
        }, {
            "target": "_self",
            "url": "#qimojiaquan",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "9",
            "name": "期末加权"
        }, {
            "target": "_self",
            "url": "#yuejiezhuan",
            "pId": "2",
            "children": [],
            "open": true,
            "id": "10",
            "name": "余额结转"
        }, {"target": "_self", "url": "#rizhi", "pId": "2", "children": [], "open": true, "id": "11", "name": "日志"}],
        "open": true,
        "id": "2",
        "name": "系统管理"
    }, {
        "target": "_self",
        "url": "#danganguanli",
        "pId": "1",
        "children": [{
            "target": "_self",
            "url": "#shangpindangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "13",
            "name": "商品档案"
        }, {
            "target": "_self",
            "url": "#cangkudangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "14",
            "name": "仓库档案"
        }, {
            "target": "_self",
            "url": "#kehudangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "15",
            "name": "客户档案"
        }, {
            "target": "_self",
            "url": "#gongyingshangdangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "16",
            "name": "供应商档案"
        }, {
            "target": "_self",
            "url": "#wanglaidangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "17",
            "name": "往来档案"
        }, {
            "target": "_self",
            "url": "#bumendangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "18",
            "name": "部门档案"
        }, {
            "target": "_self",
            "url": "#yuangongdangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "19",
            "name": "员工档案"
        }, {
            "target": "_self",
            "url": "#kuguandangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "20",
            "name": "库管档案"
        }, {
            "target": "_self",
            "url": "#yinxingziliao",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "21",
            "name": "银行资料"
        }, {
            "target": "_self",
            "url": "#zijinzhanghu",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "22",
            "name": "资金账户"
        }, {
            "target": "_self",
            "url": "#feiyongdangan",
            "pId": "12",
            "children": [],
            "open": true,
            "id": "23",
            "name": "费用档案"
        }],
        "open": true,
        "id": "12",
        "name": "档案管理"
    }, {
        "target": "_self",
        "url": "#cangkuguanli",
        "pId": "1",
        "children": [{
            "target": "_self",
            "url": "#rukudan",
            "pId": "24",
            "children": [],
            "open": true,
            "id": "25",
            "name": "入库单"
        }, {
            "target": "_self",
            "url": "#xiaohuodan",
            "pId": "24",
            "children": [],
            "open": true,
            "id": "26",
            "name": "销货单"
        }, {
            "target": "_self",
            "url": "#kucunzhuanyi",
            "pId": "24",
            "children": [],
            "open": true,
            "id": "27",
            "name": "库存转移"
        }, {
            "target": "_self",
            "url": "#kucunpandian",
            "pId": "24",
            "children": [],
            "open": true,
            "id": "28",
            "name": "库存盘点"
        }, {
            "target": "_self",
            "url": "#kucunqichu",
            "pId": "24",
            "children": [],
            "open": true,
            "id": "29",
            "name": "库存期初"
        }, {
            "target": "_self",
            "url": "#tongjifenxi",
            "pId": "24",
            "children": [{
                "target": "_self",
                "url": "#kucunshangpinzongzhang",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "31",
                "name": "库存商品总账"
            }, {
                "target": "_self",
                "url": "#kucunshangpinmingxi",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "32",
                "name": "库存商品明细"
            }, {
                "target": "_self",
                "url": "#cunhuojiecunmingxi",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "33",
                "name": "存货结存明细"
            }, {
                "target": "_self",
                "url": "#rukumingxi",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "34",
                "name": "入库明细"
            }, {
                "target": "_self",
                "url": "#xiaoshoumingxi",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "35",
                "name": "销售明细"
            }, {
                "target": "_self",
                "url": "#kucunzhuanyimingxi",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "36",
                "name": "库存转移明细"
            }, {
                "target": "_self",
                "url": "#kucunpandianmingxi",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "37",
                "name": "库存盘点明细"
            }, {
                "target": "_self",
                "url": "#kucunbaojingchaxun",
                "pId": "30",
                "children": [],
                "open": true,
                "id": "38",
                "name": "库存报警查询"
            }],
            "open": true,
            "id": "30",
            "name": "统计分析"
        }],
        "open": true,
        "id": "24",
        "name": "仓库管理"
    }, {
        "target": "_self",
        "url": "#fapiaoguanli",
        "pId": "1",
        "children": [{
            "target": "_self",
            "url": "#jinxiangfapiao",
            "pId": "39",
            "children": [],
            "open": true,
            "id": "40",
            "name": "进项发票"
        }, {
            "target": "_self",
            "url": "#xiaoxiangfapiao",
            "pId": "39",
            "children": [],
            "open": true,
            "id": "41",
            "name": "销项发票"
        }, {
            "target": "_self",
            "url": "#caigoufapiaoqichu",
            "pId": "39",
            "children": [],
            "open": true,
            "id": "42",
            "name": "采购发票期初"
        }, {
            "target": "_self",
            "url": "#xiaoshoufapiaoqichu",
            "pId": "39",
            "children": [],
            "open": true,
            "id": "43",
            "name": "销售发票期初"
        }, {
            "target": "_self",
            "url": "#tongjifenxi",
            "pId": "39",
            "children": [{
                "target": "_self",
                "url": "#caigoufapiaomingxi",
                "pId": "44",
                "children": [],
                "open": true,
                "id": "45",
                "name": "采购发票明细"
            }, {
                "target": "_self",
                "url": "#xiaoshoufapiaomingxi",
                "pId": "44",
                "children": [],
                "open": true,
                "id": "46",
                "name": "销售发票明细"
            }],
            "open": true,
            "id": "44",
            "name": "统计分析"
        }],
        "open": true,
        "id": "39",
        "name": "发票管理"
    }, {
        "target": "_self",
        "url": "#feizhuyingshouzhi",
        "pId": "1",
        "children": [{
            "target": "_self",
            "url": "#feizhuyingshouru",
            "pId": "47",
            "children": [],
            "open": true,
            "id": "48",
            "name": "非主营收入"
        }, {
            "target": "_self",
            "url": "#feizhuyingzhichu",
            "pId": "47",
            "children": [],
            "open": true,
            "id": "49",
            "name": "非主营支出"
        }, {
            "target": "_self",
            "url": "#tongjifenxi",
            "pId": "47",
            "children": [],
            "open": true,
            "id": "50",
            "name": "统计分析"
        }],
        "open": true,
        "id": "47",
        "name": "非主营收支"
    }, {
        "target": "_self",
        "url": "#zijinguanli",
        "pId": "1",
        "children": [{
            "target": "_self",
            "url": "#shoukuanjiesuan",
            "pId": "51",
            "children": [],
            "open": true,
            "id": "52",
            "name": "收款结算"
        }, {
            "target": "_self",
            "url": "#fukuanjiesuan",
            "pId": "51",
            "children": [],
            "open": true,
            "id": "53",
            "name": "付款结算"
        }, {
            "target": "_self",
            "url": "#zhanghudiaobo",
            "pId": "51",
            "children": [],
            "open": true,
            "id": "54",
            "name": "账户调拨"
        }, {
            "target": "_self",
            "url": "#tongjifenxi",
            "pId": "51",
            "children": [{
                "target": "_self",
                "url": "#gongfangwanglaimingxi",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "56",
                "name": "供方往来明细"
            }, {
                "target": "_self",
                "url": "#gongfangwanglaiyue",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "57",
                "name": "供方往来余额"
            }, {
                "target": "_self",
                "url": "#kehuwanglaimingxi",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "58",
                "name": "客户往来明细"
            }, {
                "target": "_self",
                "url": "#kehuwanglaiyue",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "59",
                "name": "客户往来余额"
            }, {
                "target": "_self",
                "url": "#bumenwanglaichaxun",
                "pId": "55",
                "children": [{
                    "target": "_self",
                    "url": "#bumenwanglaimingxi",
                    "pId": "60",
                    "children": [],
                    "open": true,
                    "id": "61",
                    "name": "部门往来明细"
                }, {
                    "target": "_self",
                    "url": "#bumenwanglaiyue",
                    "pId": "60",
                    "children": [],
                    "open": true,
                    "id": "62",
                    "name": "部门往来余额"
                }, {
                    "target": "_self",
                    "url": "#bumenyingshoumingxi63",
                    "pId": "60",
                    "children": [],
                    "open": true,
                    "id": "",
                    "name": "部门应收明细63"
                }, {
                    "target": "_self",
                    "url": "#bumenyingshouyue64",
                    "pId": "60",
                    "children": [],
                    "open": true,
                    "id": "",
                    "name": "部门应收余额64"
                }, {
                    "target": "_self",
                    "url": "#bumenyingfumingxi65",
                    "pId": "60",
                    "children": [],
                    "open": true,
                    "id": "",
                    "name": "部门应付明细65"
                }, {
                    "target": "_self",
                    "url": "#bumenyingfuyue66",
                    "pId": "60",
                    "children": [],
                    "open": true,
                    "id": "",
                    "name": "部门应付余额66"
                }],
                "open": true,
                "id": "60",
                "name": "部门往来查询"
            }, {
                "target": "_self",
                "url": "#gerenwanglaichaxun",
                "pId": "55",
                "children": [{
                    "target": "_self",
                    "url": "#gerenwanglaimingxi",
                    "pId": "67",
                    "children": [],
                    "open": true,
                    "id": "68",
                    "name": "个人往来明细"
                }, {
                    "target": "_self",
                    "url": "#gerenwanglaiyue",
                    "pId": "67",
                    "children": [],
                    "open": true,
                    "id": "69",
                    "name": "个人往来余额"
                }, {
                    "target": "_self",
                    "url": "#gerenyingshoumingxi",
                    "pId": "67",
                    "children": [],
                    "open": true,
                    "id": "70",
                    "name": "个人应收明细"
                }, {
                    "target": "_self",
                    "url": "#gerenyingshouyue",
                    "pId": "67",
                    "children": [],
                    "open": true,
                    "id": "71",
                    "name": "个人应收余额"
                }, {
                    "target": "_self",
                    "url": "#gerenyingfumingxi",
                    "pId": "67",
                    "children": [],
                    "open": true,
                    "id": "72",
                    "name": "个人应付明细"
                }, {
                    "target": "_self",
                    "url": "#gerenyingfuyue",
                    "pId": "67",
                    "children": [],
                    "open": true,
                    "id": "73",
                    "name": "个人应付余额"
                }],
                "open": true,
                "id": "67",
                "name": "个人往来查询"
            }, {
                "target": "_self",
                "url": "#qitawanglaichaxun",
                "pId": "55",
                "children": [{
                    "target": "_self",
                    "url": "#qitawanglaimingxi",
                    "pId": "74",
                    "children": [],
                    "open": true,
                    "id": "75",
                    "name": "其它往来明细"
                }, {
                    "target": "_self",
                    "url": "#qitawanglaiyue",
                    "pId": "74",
                    "children": [],
                    "open": true,
                    "id": "76",
                    "name": "其它往来余额"
                }, {
                    "target": "_self",
                    "url": "#qitayingshoumingxi",
                    "pId": "74",
                    "children": [],
                    "open": true,
                    "id": "77",
                    "name": "其它应收明细"
                }, {
                    "target": "_self",
                    "url": "#qitayingshouyue",
                    "pId": "74",
                    "children": [],
                    "open": true,
                    "id": "78",
                    "name": "其它应收余额"
                }, {
                    "target": "_self",
                    "url": "#qitayingfumingxi",
                    "pId": "74",
                    "children": [],
                    "open": true,
                    "id": "79",
                    "name": "其它应付明细"
                }, {
                    "target": "_self",
                    "url": "#qitayingfuyue",
                    "pId": "74",
                    "children": [],
                    "open": true,
                    "id": "80",
                    "name": "其它应付余额"
                }],
                "open": true,
                "id": "74",
                "name": "其它往来查询"
            }, {
                "target": "_self",
                "url": "#shoukuanjiesuanqingdan",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "81",
                "name": "收款结算清单"
            }, {
                "target": "_self",
                "url": "#fukuanjiesuanqingdan",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "82",
                "name": "付款结算清单"
            }, {
                "target": "_self",
                "url": "#zhanghushouzhimingxi",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "83",
                "name": "账户收支明细"
            }, {
                "target": "_self",
                "url": "#zhanghushouzhiyue",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "84",
                "name": "账户收支余额"
            }, {
                "target": "_self",
                "url": "#zhanghuzijinyugubiao",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "85",
                "name": "账户资金预估表"
            }, {
                "target": "_self",
                "url": "#wanglaihudimingxibiao",
                "pId": "55",
                "children": [],
                "open": true,
                "id": "86",
                "name": "往来互抵明细表"
            }],
            "open": true,
            "id": "55",
            "name": "统计分析"
        }, {
            "target": "_self",
            "url": "#fukuanfenxi",
            "pId": "51",
            "children": [{
                "target": "_self",
                "url": "#yufumingxi",
                "pId": "87",
                "children": [],
                "open": true,
                "id": "88",
                "name": "预付明细"
            }, {
                "target": "_self",
                "url": "#yufuyue",
                "pId": "87",
                "children": [],
                "open": true,
                "id": "89",
                "name": "预付余额"
            }, {
                "target": "_self",
                "url": "#yingfuyue",
                "pId": "87",
                "children": [],
                "open": true,
                "id": "90",
                "name": "应付余额"
            }],
            "open": true,
            "id": "87",
            "name": "付款分析"
        }, {
            "target": "_self",
            "url": "#shoukuanfenxi",
            "pId": "51",
            "children": [{
                "target": "_self",
                "url": "#yushoumingxi",
                "pId": "91",
                "children": [],
                "open": true,
                "id": "92",
                "name": "预收明细"
            }, {
                "target": "_self",
                "url": "#yushouyue",
                "pId": "91",
                "children": [],
                "open": true,
                "id": "93",
                "name": "预收余额"
            }, {
                "target": "_self",
                "url": "#yingfuyue",
                "pId": "91",
                "children": [],
                "open": true,
                "id": "94",
                "name": "应付余额"
            }],
            "open": true,
            "id": "91",
            "name": "收款分析"
        }],
        "open": true,
        "id": "51",
        "name": "资金管理"
    }, {
        "target": "_self",
        "url": "#juecefenxi",
        "pId": "1",
        "children": [{
            "target": "_self",
            "url": "#xiaoshoulirunbiao",
            "pId": "95",
            "children": [],
            "open": true,
            "id": "96",
            "name": "销售利润表"
        }, {
            "target": "_self",
            "url": "#picilirunbiao",
            "pId": "95",
            "children": [],
            "open": true,
            "id": "97",
            "name": "批次利润表"
        }, {
            "target": "_self",
            "url": "#jinxiaocunhuizongbiao",
            "pId": "95",
            "children": [],
            "open": true,
            "id": "98",
            "name": "进销存汇总表"
        }, {
            "target": "_self",
            "url": "#jinxiaocunhuizongbiao",
            "pId": "95",
            "children": [],
            "open": true,
            "id": "99",
            "name": "进销存汇总表"
        }],
        "open": true,
        "id": "95",
        "name": "决策分析"
    }], "open": true, "id": "1", "name": "我的工作台"
}];